stages:
  - build
  - release

build_pdf:
  stage: build
  image: blang/latex:ubuntu
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - apt-get update && apt-get install -y chktex
    - ./scripts/check_formatting.sh
    - ./scripts/check_compile.sh
    - latexmk book.tex
  artifacts:
    paths:
      - book.pdf
    expire_in: 1 week

release:
  stage: release
  needs: [build_pdf]
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Creating release $CI_COMMIT_TAG"
  release:
    tag_name: $CI_COMMIT_TAG
    name: "Release $CI_COMMIT_TAG"
    description: "Automated release"
    assets:
      paths:
        - book.pdf
